# VISUALIZAR LOS APELLIDOS DE LOS VENDEDORES, SU FECHA Y SU NUMERO DE GRUPO ORDENADO POR FECHA DESC, MOSTRAR LOS ULTIMOS 4#
SELECT apellidos, fecha_ingreso, grupo_id FROM vendedores ORDER BY fecha_ingreso;

