#OBTENER LOS NOMBRES Y LAS CIUDADES DE LOS CLIENTES QUE TENGAN ENCARGOS#
SELECT cl.id AS 'ID' ,cl.nombre AS 'NOMBRE DE CLIENTE', cl.ciudad AS 'CIUDAD' 
FROM clientes cl
INNER JOIN encargos e ON cl.id=e.cliente_id;

#OBTENER LOS NOMBRES Y LAS CIUDADES DE LOS CLIENTES QUE TENGAN ENCARGOS DE 3 UNIDADES EN ADELANTE#
SELECT cl.id AS 'ID' ,cl.nombre AS 'NOMBRE DE CLIENTE', cl.ciudad AS 'CIUDAD' 
FROM clientes cl
INNER JOIN encargos e ON cl.id=e.cliente_id
WHERE e.cantidad>=3;