/*VISUALIZAR LOS NOMBRE DE LOS CLIENTES Y LA CANTIDAD DE ENCARGOS REALIZADOS INCLUYENDO LOS QUE NO HAYAN REALIZADO ENCARGOS*/

SELECT cl.nombre AS 'CLIENTE', COUNT(e.cantidad) AS 'CANTIDAD DE ENCARGOS'
FROM clientes cl
LEFT JOIN encargos e ON cl.id=e.cliente_id
GROUP BY(cl.nombre);



