/* 
MOSTRA LOS DATOS DEL VENDEDOR CON MAS ANTIGUEDAD EN EL CONCESIONARIO
 */

INSERT INTO vendedores VALUES(null, 1, 2, 'Steven', 'Vega', 'Jefe', '2017-06-10', 35000.00, 6);

/*COMO VISUALIZAR LA INFORMACION DE UNA LLAVE PRIMARIA O SECUNDARIA*/

SELECT
  TABLE_NAME,
  COLUMN_NAME,
  CONSTRAINT_NAME,  
  REFERENCED_TABLE_NAME,
  REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
  TABLE_NAME = 'vendedores';


/* 
MOSTRA LOS DATOS DEL VENDEDOR CON MAS ANTIGUEDAD EN EL CONCESIONARIO
 */

SELECT DATEDIFF(CURDATE(),fecha_ingreso) FROM vendedores;


SELECT *, MAX(DATEDIFF(CURDATE(),fecha_ingreso)) 
FROM vendedores 
GROUP BY DATEDIFF(CURDATE(),fecha_ingreso) 
ORDER BY DATEDIFF(CURDATE(),fecha_ingreso) DESC 
LIMIT 1;

/*OBTENER LOS COCHES CON MAS UNIDADES VENDIDAS*/
SELECT * 
FROM coches 
WHERE id = (SELECT coche_id FROM encargos ORDER BY(cantidad) DESC LIMIT 1);

SELECT co.modelo AS 'MODELO',  
FROM coches co 
INNER JOIN encargos e ON co.id=e.coche_id
GROUP BY e.cantidad DESC LIMIT 1;